spring.application.name=test-bot

# ✅ Pointer le client OpenAI vers Ollama (qui tourne en local)
spring.ai.openai.base-url=http://localhost:11434
spring.ai.openai.api-key=ollama

# Modèle Ollama que tu veux utiliser
# (doit être téléchargé via : ollama pull llama3.2)
spring.ai.openai.chat.options.model=llama3.2
server.port=8087
spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp
telegram.api.key=8720615127:AAHnEnPmzzDOzazC2ry1_dv41b-HuXcrk14